PACKAGE_NAME="nitro-control-acer-wmi"
PACKAGE_VERSION="0.1.0"

AUTOINSTALL="yes"

MAKE[0]="'make' KERNELRELEASE=${kernelver}"
CLEAN="make KERNELRELEASE=${kernelver} clean"

BUILT_MODULE_NAME[0]="acer-wmi"
DEST_MODULE_LOCATION[0]="/updates/dkms"
